//go:build enterprise

package enterprise

// Package enterprise (user_store.go) implements the local user store for
// Grimlocker Enterprise. It manages authentication credentials and enforces
// the compromise-detection rules that protect the vault from brute-force attacks.
//
// Authentication Flow:
//
//	Normal Login:
//	  Client sends username + password.
//	  Server validates via Argon2id. On success: session established.
//
//	First Login:
//	  Same as normal, but the server detects FirstLogin=true.
//	  Server generates a 12-word passphrase, stores its Argon2id hash,
//	  and returns the plaintext passphrase ONCE to the client.
//	  The client must display it and the user must save it — it is NEVER shown again.
//
//	After 3 Wrong Passwords:
//	  Server enters "Passphrase Challenge" mode.
//	  If passphrase is correct: counter resets, normal login allowed.
//	  If passphrase is wrong 4 times: account is compromised.
//
//	Account Compromised (User):
//	  UserRecord is overwritten with noise via the Rust CGO wipe module.
//	  Admin is notified via SECURITY.AUDIT event.
//
//	Account Compromised (Admin):
//	  Entire vault database is overwritten with noise (TriggerHardLockdown).
//	  Daemon shuts down.
package enterprise

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sync"
	"time"

	"golang.org/x/crypto/argon2"
)

// UserStatus represents the current state of a user account.
type UserStatus string

const (
	UserActive       UserStatus = "active"
	UserLocked       UserStatus = "locked"
	UserCompromised  UserStatus = "compromised"
)

// CompromiseAction is the response to a critical auth failure.
type CompromiseAction int

const (
	NoAction          CompromiseAction = iota
	LockAccount                        // Temporary lockout
	CompromiseAccount                  // Noise-overwrite user record + admin alert
	CompromiseDatabase                 // Noise-overwrite full DB + shutdown
)

// User holds the credentials and metadata for an enterprise vault user.
// Passwords and passphrases are never stored in plaintext — only Argon2id hashes.
type User struct {
	ID       string   `json:"id"`
	Username string   `json:"username"`
	Roles    []string `json:"roles"` // ["admin"] or ["user"]

	PasswordHash []byte `json:"password_hash"` // Argon2id
	PasswordSalt []byte `json:"password_salt"`

	// Passphrase is the anti-destroy key, generated on first login.
	// It is shown to the user ONCE and never again.
	PassphraseHash []byte `json:"passphrase_hash,omitempty"`
	PassphraseSalt []byte `json:"passphrase_salt,omitempty"`

	CreatedBy  string `json:"created_by"` // Username of the creating admin
	CreatedAt  int64  `json:"created_at"`
	FirstLogin bool   `json:"first_login"` // true = passphrase not yet generated/shown

	// Failure tracking for compromise detection.
	FailedPasswordAttempts   int   `json:"failed_password_attempts"`
	LastFailedPasswordAt     int64 `json:"last_failed_password_at"`
	FailedPassphraseAttempts int   `json:"failed_passphrase_attempts"`

	Status UserStatus `json:"status"`
}

// Argon2id parameters — tuned for ~200ms on a modern CPU.
const (
	argon2Time    = 3
	argon2Memory  = 64 * 1024 // 64 MB
	argon2Threads = 2
	argon2KeyLen  = 32
)

// UserStore manages enterprise user credentials.
type UserStore struct {
	mu      sync.RWMutex
	users   map[string]*User // ID → User
	dataDir string
}

// NewUserStore creates a UserStore backed by the given directory.
func NewUserStore(dataDir string) (*UserStore, error) {
	us := &UserStore{
		users:   make(map[string]*User),
		dataDir: dataDir,
	}
	if err := us.load(); err != nil && !os.IsNotExist(err) {
		return nil, fmt.Errorf("user store load: %w", err)
	}
	return us, nil
}

// CreateUser creates a new user and returns the plaintext password ONCE.
// The password is generated by the system — it is never stored in plaintext.
// Only an admin may call this function (enforcement via RBAC at handler level).
func (us *UserStore) CreateUser(createdBy, username string, roles []string) (password string, err error) {
	us.mu.Lock()
	defer us.mu.Unlock()

	// Check duplicate username.
	for _, u := range us.users {
		if u.Username == username {
			return "", fmt.Errorf("username already exists: %s", username)
		}
	}

	// Generate a secure 12-char password: uppercase, lowercase, digits, symbols.
	password, err = generateSecurePassword(12)
	if err != nil {
		return "", fmt.Errorf("generate password: %w", err)
	}

	salt := make([]byte, 16)
	if _, err := rand.Read(salt); err != nil {
		return "", fmt.Errorf("generate salt: %w", err)
	}

	hash := argon2.IDKey([]byte(password), salt, argon2Time, argon2Memory, argon2Threads, argon2KeyLen)

	id := generateUserID()
	u := &User{
		ID:           id,
		Username:     username,
		Roles:        roles,
		PasswordHash: hash,
		PasswordSalt: salt,
		CreatedBy:    createdBy,
		CreatedAt:    time.Now().UnixNano(),
		FirstLogin:   true,
		Status:       UserActive,
	}

	us.users[id] = u
	if err := us.saveLocked(); err != nil {
		delete(us.users, id)
		return "", fmt.Errorf("save user store: %w", err)
	}

	log.Printf("[UserStore] Created user=%q id=%s by admin=%s roles=%v",
		username, id[:8], createdBy, roles)
	return password, nil
}

// AuthenticatePassword validates a username + password pair.
// On first login: generates the passphrase and returns it ONCE.
// On subsequent logins: returns ("", nil) on success.
// Returns (nil, "", error) on auth failure.
func (us *UserStore) AuthenticatePassword(username, password string) (
	user *User, firstLoginPassphrase string, err error,
) {
	us.mu.Lock()
	defer us.mu.Unlock()

	u := us.findByUsernameLocked(username)
	if u == nil {
		return nil, "", fmt.Errorf("invalid credentials")
	}
	if u.Status != UserActive {
		return nil, "", fmt.Errorf("account is %s", u.Status)
	}

	expected := argon2.IDKey([]byte(password), u.PasswordSalt, argon2Time, argon2Memory, argon2Threads, argon2KeyLen)
	if !constantTimeEqual(expected, u.PasswordHash) {
		return nil, "", fmt.Errorf("invalid credentials")
	}

	// Successful auth — reset failure counters.
	u.FailedPasswordAttempts = 0
	u.LastFailedPasswordAt = 0

	// First login: generate and store passphrase, return it ONCE.
	if u.FirstLogin {
		passphrase, err := GeneratePassphrase(12)
		if err != nil {
			return nil, "", fmt.Errorf("generate passphrase: %w", err)
		}

		ppSalt := make([]byte, 16)
		if _, err := rand.Read(ppSalt); err != nil {
			return nil, "", fmt.Errorf("generate passphrase salt: %w", err)
		}

		ppHash := argon2.IDKey([]byte(passphrase), ppSalt, argon2Time, argon2Memory, argon2Threads, argon2KeyLen)
		u.PassphraseHash = ppHash
		u.PassphraseSalt = ppSalt
		u.FirstLogin = false

		if err := us.saveLocked(); err != nil {
			return nil, "", fmt.Errorf("save after first login: %w", err)
		}

		log.Printf("[UserStore] First login for user=%q — passphrase generated and shown", username)
		return u, passphrase, nil
	}

	if err := us.saveLocked(); err != nil {
		log.Printf("[UserStore] WARNING: failed to persist auth success: %v", err)
	}
	return u, "", nil
}

// RecordPasswordFailure records a failed password attempt.
// After 3 failures, returns CompromiseChallenge — the caller should prompt for passphrase.
func (us *UserStore) RecordPasswordFailure(userID string) (CompromiseAction, error) {
	us.mu.Lock()
	defer us.mu.Unlock()

	u, ok := us.users[userID]
	if !ok {
		return NoAction, fmt.Errorf("user not found: %s", userID)
	}

	u.FailedPasswordAttempts++
	u.LastFailedPasswordAt = time.Now().UnixNano()

	log.Printf("[UserStore] Password failure user=%q attempts=%d", u.Username, u.FailedPasswordAttempts)

	_ = us.saveLocked()

	if u.FailedPasswordAttempts >= 3 {
		// Signal the caller to present a passphrase challenge.
		// We don't lock/compromise yet — that happens in VerifyPassphrase.
		return LockAccount, nil
	}
	return NoAction, nil
}

// VerifyPassphrase verifies the passphrase entered after 3 wrong passwords.
// Correct: resets failure counter. Wrong 4x: CompromiseAccount or CompromiseDatabase.
func (us *UserStore) VerifyPassphrase(userID, passphrase string) (CompromiseAction, error) {
	us.mu.Lock()
	defer us.mu.Unlock()

	u, ok := us.users[userID]
	if !ok {
		return NoAction, fmt.Errorf("user not found: %s", userID)
	}

	expected := argon2.IDKey(
		[]byte(passphrase), u.PassphraseSalt,
		argon2Time, argon2Memory, argon2Threads, argon2KeyLen,
	)

	if constantTimeEqual(expected, u.PassphraseHash) {
		// Correct passphrase — reset all failure counters.
		u.FailedPasswordAttempts = 0
		u.FailedPassphraseAttempts = 0
		u.LastFailedPasswordAt = 0
		log.Printf("[UserStore] Passphrase verified for user=%q — counters reset", u.Username)
		_ = us.saveLocked()
		return NoAction, nil
	}

	// Wrong passphrase.
	u.FailedPassphraseAttempts++
	log.Printf("[UserStore] Wrong passphrase user=%q attempt=%d/4", u.Username, u.FailedPassphraseAttempts)

	if u.FailedPassphraseAttempts >= 4 {
		u.Status = UserCompromised
		log.Printf("[UserStore] ACCOUNT COMPROMISED: user=%q roles=%v", u.Username, u.Roles)
		_ = us.saveLocked()

		// Determine compromise level: admin → full DB, user → account only.
		for _, role := range u.Roles {
			if role == "admin" {
				return CompromiseDatabase, nil
			}
		}
		return CompromiseAccount, nil
	}

	_ = us.saveLocked()
	return NoAction, nil
}

// MarkFirstLoginComplete is idempotent — called to confirm the user has acknowledged
// seeing their passphrase.
func (us *UserStore) MarkFirstLoginComplete(userID string) error {
	us.mu.Lock()
	defer us.mu.Unlock()
	u, ok := us.users[userID]
	if !ok {
		return fmt.Errorf("user not found: %s", userID)
	}
	u.FirstLogin = false
	return us.saveLocked()
}

// UpdateStatus changes the status of a user account.
func (us *UserStore) UpdateStatus(userID string, status UserStatus) error {
	us.mu.Lock()
	defer us.mu.Unlock()
	u, ok := us.users[userID]
	if !ok {
		return fmt.Errorf("user not found: %s", userID)
	}
	u.Status = status
	return us.saveLocked()
}

// ListUsers returns all users (without sensitive hash fields for wire serialization).
func (us *UserStore) ListUsers() []User {
	us.mu.RLock()
	defer us.mu.RUnlock()
	result := make([]User, 0, len(us.users))
	for _, u := range us.users {
		// Return a copy with hashes stripped for safety.
		safe := *u
		safe.PasswordHash = nil
		safe.PasswordSalt = nil
		safe.PassphraseHash = nil
		safe.PassphraseSalt = nil
		result = append(result, safe)
	}
	return result
}

// RestoreUser resets a compromised account to active status (Admin-only).
// The account will need a new password generated by CreateUser after restore.
func (us *UserStore) RestoreUser(adminID, userID string) error {
	us.mu.Lock()
	defer us.mu.Unlock()

	u, ok := us.users[userID]
	if !ok {
		return fmt.Errorf("user not found: %s", userID)
	}
	if u.Status != UserCompromised {
		return fmt.Errorf("user is not in compromised state (status=%s)", u.Status)
	}

	// Reset all state; admin must re-create credentials.
	u.Status = UserActive
	u.FailedPasswordAttempts = 0
	u.FailedPassphraseAttempts = 0
	u.LastFailedPasswordAt = 0
	// Force re-login flow: mark first login so new password is set.
	u.FirstLogin = true

	log.Printf("[UserStore] Account restored: user=%q by admin=%s", u.Username, adminID)
	return us.saveLocked()
}

// findByUsernameLocked finds a user by username. Caller must hold us.mu.
func (us *UserStore) findByUsernameLocked(username string) *User {
	for _, u := range us.users {
		if u.Username == username {
			return u
		}
	}
	return nil
}

// persistPath returns the path to the encrypted user store file.
func (us *UserStore) persistPath() string {
	return filepath.Join(us.dataDir, "enterprise_users.json")
}

func (us *UserStore) load() error {
	data, err := os.ReadFile(us.persistPath())
	if err != nil {
		return err
	}
	var users []*User
	if err := json.Unmarshal(data, &users); err != nil {
		return err
	}
	for _, u := range users {
		us.users[u.ID] = u
	}
	return nil
}

func (us *UserStore) saveLocked() error {
	users := make([]*User, 0, len(us.users))
	for _, u := range us.users {
		users = append(users, u)
	}
	data, err := json.Marshal(users)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(us.dataDir, 0700); err != nil {
		return err
	}
	tmp := us.persistPath() + ".tmp"
	if err := os.WriteFile(tmp, data, 0600); err != nil {
		return err
	}
	return os.Rename(tmp, us.persistPath())
}

// generateUserID creates a short random user ID (16 hex chars).
func generateUserID() string {
	b := make([]byte, 8)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

// generateSecurePassword creates a random password from a mixed character set.
func generateSecurePassword(length int) (string, error) {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()"
	result := make([]byte, length)
	for i := range result {
		b := make([]byte, 1)
		for {
			if _, err := rand.Read(b); err != nil {
				return "", err
			}
			if int(b[0]) < len(charset)*(256/len(charset)) {
				result[i] = charset[int(b[0])%len(charset)]
				break
			}
		}
	}
	return string(result), nil
}

// constantTimeEqual compares two byte slices in constant time.
func constantTimeEqual(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	var v byte
	for i := range a {
		v |= a[i] ^ b[i]
	}
	return v == 0
}
